export const mentorData = [
  {
    mentorId: "tanay_pratap",
    name: "Tanay Praap",
    cateogry: "Tech Mentor",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",
    banner: "https://i.ibb.co/hX5SQyj/tanay.png",
    playlist: [
      { id: "tea_with_tanay", name: "Tea with Tanay" },
      { id: "carrer_moves", name: "Carrer Moves" },
      { id: "neog_camp", name: "Neog Camp" },
    ],
  },

  {
    mentorId: "varun_mavya",
    name: "Varun Mavya",
    cateogry: "Business Mentor",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    banner: "https://i.ibb.co/q5RsVZg/varun.png",

    playlist: [
      { id: "meta_startup", name: "Meta Start up" },
      { id: "cero", name: "Cero" },
    ],
  },

  {
    mentorId: "shashank_udupa",
    name: "Shashank Udupa",
    cateogry: "Finance Mentor",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    banner: "https://i.ibb.co/WBVvb2x/shashank.png",
    playlist: [
      { id: "world_of_finance", name: "World of Finance" },
      { id: "ipo_review", name: "IPO Review" },
    ],
  },
  {
    mentorId: "abhinav_gupta",
    name: "Abhinav Gupta",
    cateogry: "Marketing Mentor",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    banner: "https://i.ibb.co/VSpbTVQ/abhinav.png",
    playlist: [{ id: "abhinav_podcasts", name: "Podcasts" }],
  },

  {
    mentorId: "abhinav_chikara",
    name: "Abhinav Chikara",
    cateogry: "Design Mentor",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    banner: "https://i.ibb.co/sy1bMvD/abhinav-Chikara.png",
    playlist: [
      { id: "interview_with_designers", name: "Interview With designer's" },
      { id: "design_crash_course", name: "Design Crash Course" },
    ],
  },
  {
    mentorName: "Prakhar Gupta",
    mentorId: "prakhar_gupta",
    name: "Prakhar Gupta",
    cateogry: "Conversation Mentor",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    banner: "https://i.ibb.co/rZLyzWL/prakhar.png",
    playlist: [
      { id: "papa_ke_pravachan", name: "Papa ke Pravachan" },
      { id: "spirituality", name: "Spirituality" },
      { id: "live_talks", name: "Live Talks" },
    ],
  },
];

export const videos = [
  {
    title: "Design terms you should know",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/omKQsOPAjjk",
    thumbnail: "https://i.ibb.co/vjNmg8S/maxresdefault.jpg",
    category: { id: "design_crash_course", index: 1 },
    liked: false,
    views: 92943,
  },

  {
    title: "Steps in the design process",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/oSz5KTdKW88",
    thumbnail: "https://i.ibb.co/gFrJhW7/maxresdefault-1.jpg",
    category: { id: "design_crash_course", index: 2 },
    liked: false,
    views: 92943,
  },

  {
    title: "How to develop an eye for good design",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/T4BvVOC_J_k",
    thumbnail: "https://i.ibb.co/k0m2XjM/maxresdefault-2.jpg",
    category: { id: "design_crash_course", index: 3 },
    liked: false,
    views: 92943,
  },

  {
    title: "Learn UI design in 25 minutes - Figma tutorial",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/RKILkYOHRXk",
    thumbnail: "https://i.ibb.co/4skVvwh/maxresdefault-3.jpg",
    category: { id: "design_crash_course", index: 4 },
    liked: false,
    views: 92943,
  },

  {
    title: "The best way to practice design - Part 1",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/pBgufXz2lbU",
    thumbnail: "https://i.ibb.co/CVFJ29R/maxresdefault-4.jpg",
    category: { id: "design_crash_course", index: 5 },
    liked: false,
    views: 92943,
  },

  {
    title: "Practice design by copying - Part 2",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/lEfyEbwfi0k",
    thumbnail: "https://i.ibb.co/FK1hMW4/maxresdefault-5.jpg",
    category: { id: "design_crash_course", index: 6 },
    liked: false,
    views: 92943,
  },

  {
    title: "Sketch, Adobe XD or Figma?",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/bUFjEPOO488",
    thumbnail: "https://i.ibb.co/brVKWkK/maxresdefault-6.jpg",
    category: { id: "design_crash_course", index: 7 },
    liked: false,
    views: 92943,
  },

  {
    title:
      "Live Design Case Studies with King Sidharth, Product & Design @ Headout | Design & Process stream",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/jdne_SwILSQ",
    thumbnail: "https://i.ibb.co/m5G3Lj2/maxresdefault-5.jpg",
    category: { id: "interview_with_designers", index: 1 },
    liked: false,
    views: 92943,
  },

  {
    title:
      "Design Q&A with Darshan Gajara, design consultant and founder of Product Disrupt",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/m2T1aPfshnk",
    thumbnail: "https://i.ibb.co/hMgQcyN/maxresdefault-3.jpg",
    category: { id: "interview_with_designers", index: 2 },
    liked: false,
    views: 92943,
  },

  {
    title: "Design Q&A with Shashank Sahay, Designer at Microsoft",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/rYkFQLSSaIM",
    thumbnail: "https://i.ibb.co/VVdN3WD/maxresdefault-2.jpg",
    category: { id: "interview_with_designers", index: 3 },
    liked: false,
    views: 92943,
  },

  {
    title: "Design Q&A with Saptarshi Prakash, Lead Designer at Swiggy",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/soBEttAoTGw",
    thumbnail: "https://i.ibb.co/RHnTQDJ/maxresdefault-1.jpg",
    category: { id: "interview_with_designers", index: 4 },
    liked: false,
    views: 92943,
  },

  {
    title: "Design Q&A with Abheyraj Singh, designer at GoEuro Berlin",
    mentorName: "Abhinav Chikara",
    mentorId: "abhinav_chikara",
    profile: "  https://i.ibb.co/j3p6ZxS/abhinav-Chikara.png",
    embededLink: "https://www.youtube.com/embed/agXAcxQvAxI",
    thumbnail: "https://i.ibb.co/JKtc5rn/maxresdefault.jpg",
    category: { id: "interview_with_designers", index: 5 },
    liked: false,
    views: 92943,
  },

  {
    title: "The Future of Media Entrepreneurship @SIMC, PUNE",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/bOMrGECs7kI",
    thumbnail: "https://i.ibb.co/4Kj8B50/maxresdefault-6.jpg",
    category: { id: "live_talks", index: 1 },
    liked: false,
    views: 92943,
  },

  {
    title: "LIVE FROM IIT ROORKEE- THE SECRET TO HAVING GREAT CONVERSATIONS",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/Lr0i3_pFDPo",
    thumbnail: "https://i.ibb.co/xLY0rP8/maxresdefault-5.jpg",
    category: { id: "live_talks", index: 2 },
    liked: false,
    views: 72043,
  },

  {
    title: "LIVE FROM DELHI TECHNOLOGICAL UNIVERSITY",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/gQKIIq91EAA",
    thumbnail: "https://i.ibb.co/nj7cPsx/maxresdefault-4.jpg",
    category: { id: "live_talks", index: 3 },
    liked: false,
    views: 92043,
  },

  {
    title: "LIVE FROM SVC, DELHI UNIVERSITY",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/mhsKuUNLACY",
    thumbnail: "https://i.ibb.co/4jWsjXh/maxresdefault-3.jpg",
    category: { id: "live_talks", index: 4 },
    liked: false,
    views: 92043,
  },

  {
    title: "STEREOTYPES, SOCIETY and the YOUTUBE DADDY",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/-0agIi5sIxU",
    thumbnail: "https://i.ibb.co/WFw1W6H/maxresdefault-2.jpg",
    category: { id: "live_talks", index: 5 },
    liked: false,
    views: 92043,
  },

  {
    title: "Prakhar's Advice to Genz | Dealing with Procrastination & Failure",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/LkoP00u4G4A",
    thumbnail: "https://i.ibb.co/Nyyrjzh/maxresdefault-1.jpg",
    category: { id: "live_talks", index: 6 },
    liked: false,
    views: 92043,
  },

  {
    title: "How to Develop a STRONG MINDSET to Combat Hard Times",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/iydrZ6yxjZI",
    thumbnail: "https://i.ibb.co/9NZpT8V/maxresdefault.jpg",
    category: { id: "live_talks", index: 7 },
    liked: false,
    views: 92043,
  },

  {
    title: "THE SPIRITUALITY OF SELF",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/efcWCrmICNI",
    thumbnail: "https://i.ibb.co/C6GGgJs/maxresdefault-3.jpg",
    category: { id: "spirituality", index: 1 },
    liked: false,
    views: 92043,
  },
  {
    title: "THE PROBLEM WITH MODERN SPIRITUALITY",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/ZkB3N6K80GI",
    thumbnail: "https://i.ibb.co/zPGY6ns/maxresdefault-2.jpg",
    category: { id: "spirituality", index: 2 },
    liked: false,
    views: 92043,
  },
  {
    title: "Prakhar takes a shit on 'spirituality'",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/G_A2LVW1Vrk",
    thumbnail: "https://i.ibb.co/YZcM2P2/maxresdefault-1.jpg",
    category: { id: "spirituality", index: 3 },
    liked: false,
    views: 92043,
  },
  {
    title: "#1 Secret to STAY CALM",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/k0QYSKLY4tE",
    thumbnail: "https://i.ibb.co/NYypQV8/maxresdefault.jpg",
    category: { id: "spirituality", index: 4 },
    liked: false,
    views: 92043,
  },

  {
    title: "THIS WILL CHANGE YOUR SOCIAL LIFE | PAPA KE PRAVACHAN EP4",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/VSduGJo0CuU",
    thumbnail: "https://i.ibb.co/74xSGJF/maxresdefault-3.jpg",
    category: { id: "papa_ke_pravachan", index: 1 },
    liked: false,
    views: 92043,
  },

  {
    title: "MANAGE YOUR TIME TO WIN LONG TERM | PAPA KE PRAVACHAN EP3",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/tIeCQOcSP98",
    thumbnail: "https://i.ibb.co/CwqBG28/maxresdefault-2.jpg",
    category: { id: "papa_ke_pravachan", index: 2 },
    liked: false,
    views: 92043,
  },

  {
    title: "SUCCESS KA 2 STEP FORMULA| PAPA KE PRAVACHAN",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/vpr9fIaSHmw",
    thumbnail: "https://i.ibb.co/PYMY3S4/maxresdefault-1.jpg",
    category: { id: "papa_ke_pravachan", index: 3 },
    liked: false,
    views: 92043,
  },

  {
    title: "LIFE IS TOUGH, MAKE THE MOST OF IT | PAPA KE PRAVACHAN EP2",
    mentorName: "Prakhar Gupta",
    profile: "https://i.ibb.co/ckvX6V1/prakhar.png",
    mentorId: "prakhar_gupta",
    embededLink: "https://www.youtube.com/embed/vVViUhyXLZA",
    thumbnail: "https://i.ibb.co/KKvYXbq/maxresdefault.jpg",
    category: { id: "papa_ke_pravachan", index: 4 },
    liked: false,
    views: 92043,
  },

  {
    title: "You're Playing This Game (Without Even Realizing)",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/XWFGOAjDx9w",
    thumbnail: "https://i.ibb.co/SmmbJPk/maxresdefault-11.jpg",
    category: { id: "abhinav_podcasts", index: 1 },
    liked: false,
    views: 92043,
  },

  {
    title: "The Mindset Shift You Need In Your 20s (MUST WATCH!)",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/npWiCWFsJ8A",
    thumbnail: "https://i.ibb.co/dm01ykY/maxresdefault-10.jpg",
    category: { id: "abhinav_podcasts", index: 2 },
    liked: false,
    views: 12043,
  },

  {
    title:
      "Social Media Scam: Are We Slave To The Algorithm? ft. @Sirhud Kalra",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/2kjiOVflcYU",
    thumbnail: "https://i.ibb.co/Cm6CX2F/maxresdefault-9.jpg",
    category: { id: "abhinav_podcasts", index: 3 },
    liked: false,
    views: 72043,
  },

  {
    title: "A Billionaire's Take on Money, Space & Healthcare ft. @Naveen Jain",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/YceBBkLvXsw",
    thumbnail: "https://i.ibb.co/5njMBpK/maxresdefault-7.jpg",
    category: { id: "abhinav_podcasts", index: 4 },
    liked: false,
    views: 24043,
  },

  {
    title: "How Can Creators Get Paid More ft. @Prakhar ke Pravachan",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/tEb26KfFvpU",
    thumbnail: "https://i.ibb.co/fQKwQWX/maxresdefault-6.jpg",
    category: { id: "abhinav_podcasts", index: 5 },
    liked: false,
    views: 12043,
  },

  {
    title: "The @Nas Daily Story & Tips For Content Creators",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/YDmnuQ1T9k4",
    thumbnail: "https://i.ibb.co/QPpt1vJ/maxresdefault-5.jpg",
    category: { id: "abhinav_podcasts", index: 6 },
    liked: false,
    views: 92043,
  },

  {
    title:
      "Sales Vs Marketing - Who Will Win? ft. Mohit Ahuja & @Vaibhav Sisinty",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/Aa4cjtR7snY",
    thumbnail: "https://i.ibb.co/FWBXGyq/maxresdefault-4.jpg",
    category: { id: "abhinav_podcasts", index: 7 },
    liked: false,
    views: 12043,
  },

  {
    title:
      "Nostalgic Ads That Will Take You Back to Childhood ft. @Mad Over Marketing (M.O.M)",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/ZPXsnVpaQ2Y",
    thumbnail: "https://i.ibb.co/TY6VDNN/maxresdefault-2.jpg",
    category: { id: "abhinav_podcasts", index: 8 },
    liked: false,
    views: 32043,
  },

  {
    title:
      "BECOME AN INFLUENCER IN YOUR 20s ft. @Raj Shamani Vs @Divyanshu Damani",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/BdTAFtwm5Fo",
    thumbnail: "https://i.ibb.co/SfnQP7H/maxresdefault-1.jpg",
    category: { id: "abhinav_podcasts", index: 9 },
    liked: false,
    views: 92043,
  },

  {
    title:
      "Life is a gamble? Lessons for Life from the Poker Table ft. Arnold Mascarenhas",
    mentorName: "Abhinav Gupta",
    mentorId: "abhinav_gupta",
    profile: "https://i.ibb.co/x7jd1x9/abhinav.png",
    embededLink: "https://www.youtube.com/embed/n5J2daZ9xWE",
    thumbnail: "https://i.ibb.co/9NshJM2/maxresdefault.jpg",
    category: { id: "abhinav_podcasts", index: 10 },
    liked: false,
    views: 19043,
  },

  {
    title: "Zomato IPO Review 2021",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/jp_yX0EG7PE",
    thumbnail: "https://i.ibb.co/P1kMjJw/maxresdefault.jpg",
    category: { id: "ipo_review", index: 1 },
    liked: false,
    views: 22543,
  },

  {
    title: "Burger King IPO with @Shashank Udupa ft. Dr. Elson",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/fYhS8MFPiUw",
    thumbnail: "https://i.ibb.co/J3M6s82/maxresdefault-1.jpg",
    category: { id: "ipo_review", index: 2 },
    liked: false,
    views: 22543,
  },

  {
    title: "How To Read Company Financials",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/mIoHSQxSGpI",
    thumbnail: "https://i.ibb.co/pzHRZ92/m-Io-HSQx-SGp-I-HD.jpg",
    category: { id: "world_of_finance", index: 1 },
    liked: false,
    views: 22543,
  },
  {
    title: "Understanding Health Insurance | smallcase Review | 2021",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/hum8D2hSoKg",
    thumbnail: "https://i.ibb.co/5B7rJHL/hum8-D2h-So-Kg-HD-1.jpg",
    category: { id: "world_of_finance", index: 2 },
    liked: false,
    views: 22543,
  },

  {
    title: "What's Happening With Gold? | smallcase Review | 2021",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/_yRgmRM1LDM",
    thumbnail: "https://i.ibb.co/D9Td49J/y-Rgm-RM1-LDM-HD.jpg",
    category: { id: "world_of_finance", index: 3 },
    liked: false,
    views: 22543,
  },

  {
    title: "Buy Real Estate Or REIT It In 2021?",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/n4hB-nSrrtE",
    thumbnail: "https://i.ibb.co/QrqJ2kB/n4h-B-n-Srrt-E-HD.jpg",
    category: { id: "world_of_finance", index: 4 },
    liked: false,
    views: 22543,
  },

  {
    title:
      "Investing In 20s Simplified | Top 3 Tools For Fundamental Analysis Of Growth Stocks - Ep. 3 | 2021",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/rT-kPOy4irM",
    thumbnail: "https://i.ibb.co/gVpqKv0/r-T-k-POy4ir-M-HD.jpg",
    category: { id: "world_of_finance", index: 5 },
    liked: false,
    views: 22543,
  },

  {
    title:
      "Investing In Your 20s Simplified - 2021 by @Shashank Udupa | Episode 1",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/qsCUE7kzFHA",
    thumbnail: "https://i.ibb.co/1vPJ8GL/qs-CUE7kz-FHA-HD.jpg",
    category: { id: "world_of_finance", index: 6 },
    liked: false,
    views: 22543,
  },

  {
    title: "Elon Buys Bitcoin, Dogecoin Up - What's Happening?",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/R7b_VzfVmb0",
    thumbnail: "https://i.ibb.co/w07z5kK/R7b-Vzf-Vmb0-HD.jpg",
    category: { id: "world_of_finance", index: 7 },
    liked: false,
    views: 22543,
  },

  {
    title: "Budget 2021 India - Is it good for you?",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/wwWf2sNxEKQ",
    thumbnail: "https://i.ibb.co/Ld9WqqP/ww-Wf2s-Nx-EKQ-HD.jpg",
    category: { id: "world_of_finance", index: 8 },
    liked: false,
    views: 22543,
  },

  {
    title: "Stock market crash in 2021?? Time to be careful!",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/EQ32FlhSCZw",
    thumbnail: "https://i.ibb.co/3k1gBH5/EQ32-Flh-SCZw-HD.jpg",
    category: { id: "world_of_finance", index: 9 },
    liked: false,
    views: 22543,
  },

  {
    title: "Should you buy Tesla Stock in 2021?",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/zeBZACg9-v4",
    thumbnail: "https://i.ibb.co/gPNcDYk/ze-BZACg9-v4-HD.jpg",
    category: { id: "world_of_finance", index: 10 },
    liked: false,
    views: 22543,
  },

  {
    title: "What To Expect From Budget 2021? (And Why You Should Care)",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/LwuHJ6BCiSs",
    thumbnail: "https://i.ibb.co/X714WXC/Lwu-HJ6-BCi-Ss-HD.jpg",
    category: { id: "world_of_finance", index: 11 },
    liked: false,
    views: 22543,
  },

  {
    title: "Bitcoin. Boom or Bubble?",
    mentorName: "Shashank Udupa",
    mentorId: "shashank_udupa",
    profile: "https://i.ibb.co/fYGG436/shashank.png",
    embededLink: "https://www.youtube.com/embed/rU8mVb_bc-M",
    thumbnail: "https://i.ibb.co/8YJJM6n/r-U8m-Vb-bc-M-HD.jpg",
    category: { id: "world_of_finance", index: 12 },
    liked: false,
    views: 22543,
  },

  {
    title: "How to make a Human Apex Predator",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/urhMZSeG33U",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 1 },
    liked: false,
    views: 22543,
  },
  {
    title: "Are we in a Simulation? Probably not.",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/FpwUqfhwwFQ",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 2 },
    liked: false,
    views: 22213,
  },
  {
    title: "The Big Bang is still happening",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/MEPBV_DBFII",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 3 },
    liked: false,
    views: 22043,
  },

  {
    title: "Quantum Suicide",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/4KnVmju4EeQ",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 4 },
    liked: false,
    views: 22593,
  },
  {
    title: "Why children NEED fairytales",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/HzMqVulxBCM",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 5 },
    liked: false,
    views: 92543,
  },
  {
    title: "Indian Superman",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/7pYhPm5IKkY",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 6 },
    liked: false,
    views: 72543,
  },
  {
    title: "Physics IS Spirituality",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/XIaIptj-Xd4",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 7 },
    liked: false,
    views: 22533,
  },
  {
    title: "Instagram is the best example of the Peak Shift effect",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/eDIuH_Q2cxw",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 8 },
    liked: false,
    views: 22043,
  },
  {
    title: "What if Mickey Mouse was conscious?",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/LLCeoDxBuig",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 9 },
    liked: false,
    views: 22511,
  },
  {
    title: "Why young entrepreneurs are arrogant",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/RFkCt4iJIIo",
    thumbnail: "https://i.ibb.co/5cpfMX0/maxresdefault.jpg",
    category: { id: "cero", index: 10 },
    liked: false,
    views: 15421,
  },

  {
    title: "METASTARTUP Episode 1: My Story",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/mB5kuXNi0xs",
    thumbnail: "https://i.ibb.co/NrVCnmC/sddefault.jpg",
    category: { id: "meta_startup", index: 1 },
    liked: false,
    views: 22543,
  },
  {
    title: "METASTARTUP Episode 2: Why you SHOULDN'T startup",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/p5nemzWv2pg",
    thumbnail: "https://i.ibb.co/NrVCnmC/sddefault.jpg",
    category: { id: "meta_startup", index: 2 },
    liked: false,
    views: 127213,
  },
  {
    title: "STARTUPS VS STABLE JOBS - YOUR JOB IS NOT SECURE | METASTARTUP #3",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/VYw3XqvLU6w",
    thumbnail: "https://i.ibb.co/NrVCnmC/sddefault.jpg",
    category: { id: "meta_startup", index: 3 },
    liked: false,
    views: 12432,
  },
  {
    title: "HOW MUCH CAPITAL DO YOU NEED TO STARTUP | METASTARTUP #4",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/iaoTQTWF940",
    thumbnail: "https://i.ibb.co/NrVCnmC/sddefault.jpg",
    category: { id: "meta_startup", index: 4 },
    liked: false,
    views: 123303,
  },
  {
    title: "HOW TO NAME YOUR STARTUP | METASTARTUP #5",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/EdRcKb2541o",
    thumbnail: "https://i.ibb.co/NrVCnmC/sddefault.jpg",
    category: { id: "meta_startup", index: 5 },
    liked: false,
    views: 32343,
  },
  {
    title: "HOW TO REGISTER A COMPANY IN INDIA? | METASTARTUP #6",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/-GVlwruv7Tg",
    thumbnail: "https://i.ibb.co/cJ7pCDx/maxresdefault.jpg",
    category: { id: "meta_startup", index: 6 },
    liked: false,
    views: 32343,
  },
  {
    title:
      "OPENING A CORPORATE BANK ACCOUNT, CREDIT CARDS, FIRST BOARD MEETING & MORE | METASTARTUP #7",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/WxMgSg_BpPI",
    thumbnail: "https://i.ibb.co/xhdRj7K/maxresdefault.jpg",
    category: { id: "meta_startup", index: 7 },
    liked: false,
    views: 12643,
  },

  {
    title:
      "REGISTERING A COMPANY IN SINGAPORE, USA OR ESTONIA | METASTARTUP #8",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/azSErrdqgbU",
    thumbnail: "https://i.ibb.co/wyt7FRJ/maxresdefault-1.jpg",
    category: { id: "meta_startup", index: 8 },
    liked: false,
    views: 12043,
  },

  {
    title: "HOW TO RAISE A SEED ROUND FOR A STARTUP IN INDIA? | METASTARTUP #9",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/tR1mLfs2Xqo",
    thumbnail: "https://i.ibb.co/0GP3sVw/maxresdefault-2.jpg",
    category: { id: "meta_startup", index: 9 },
    liked: false,
    views: 42343,
  },

  {
    title: "HOW TO RAISE A SERIES A IN INDIA | METASTARTUP #10",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/eT3tW-vXnUU",
    thumbnail: "https://i.ibb.co/Lk0VvHF/maxresdefault-3.jpg",
    category: { id: "meta_startup", index: 10 },
    liked: false,
    views: 22743,
  },
  {
    title: "HOW TO DO AN INITIAL PUBLIC OFFERING | METASTARTUP #11",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/-pYCFSEQTFo",
    thumbnail: "https://i.ibb.co/Cncxj1T/maxresdefault-4.jpg",
    category: { id: "meta_startup", index: 11 },
    liked: false,
    views: 12043,
  },
  {
    title: "BANKRUPTCY AND LIQUIDATION | METASTARTUP #12",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/kByAtHlrjQ4",
    thumbnail: "https://i.ibb.co/Qd8TbdG/maxresdefault-5.jpg",
    category: { id: "meta_startup", index: 12 },
    liked: false,
    views: 22343,
  },

  {
    title: "HOW TO SELL YOUR COMPANY + TIPS ON VALUATION | METASTARTUP #13",
    mentorName: "Varun Mavya",
    mentorId: "varun_mavya",
    profile: "https://i.ibb.co/h9jXyHZ/varun.png",
    embededLink: "https://www.youtube.com/embed/w-r8VYhxYYg",
    thumbnail: "https://i.ibb.co/zRynrNT/maxresdefault-6.jpg",
    category: { id: "meta_startup", index: 13 },
    liked: false,
    views: 22343,
  },

  {
    title: "S01E00 TeaWithTanay. Why, what and how of this new podcast series!",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/GDYhoRbYH3o",
    thumbnail: "https://i.ibb.co/N11Cz5D/maxresdefault-4.jpg",
    category: { id: "tea_with_tanay", index: 1 },
    liked: false,
    views: 12343,
  },

  {
    title:
      "14 Books for Growth and Startups ft. Priyadeep Sinha | Episode 01 of teawithtanay",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/5ZZG4SOzPkw",
    thumbnail: "https://i.ibb.co/QCgG0Jz/maxresdefault-3.jpg",
    category: { id: "tea_with_tanay", index: 2 },
    liked: false,
    views: 22343,
  },

  {
    title:
      "Programming Projects ft. Rachit Gulati | TeaWithTanay Podcast Season 1 Episode 2",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/PU4zArf71Yg",
    thumbnail: "https://i.ibb.co/ZcNGkgH/maxresdefault-2.jpg",
    category: { id: "tea_with_tanay", index: 3 },
    liked: false,
    views: 12322,
  },

  {
    title:
      "Building Communities ft. Anubha from GirlScript | TeaWithTanay Podcast Season 1 Episode 3",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/cXFMlxKx9A8",
    thumbnail: "https://i.ibb.co/CPvTpHQ/maxresdefault-1.jpg",
    category: { id: "tea_with_tanay", index: 4 },
    liked: false,
    views: 12322,
  },

  {
    title:
      "Getting Started with Open Source ft. Rahul Kadyan | S01 EP4 of teawithtanay",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/QhnU7kO8u_I",
    thumbnail: "https://i.ibb.co/n0pkWjY/maxresdefault.jpg",
    category: { id: "tea_with_tanay", index: 5 },
    liked: false,
    views: 12322,
  },

  {
    title: "Web Dev Projects to get you a job?",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/Vrwltd0y7p0",
    thumbnail: "https://i.ibb.co/0hLMKr6/maxresdefault.jpg",
    category: { id: "carrer_moves", index: 1 },
    liked: false,
    views: 12343,
  },

  {
    title: "Internships or not?",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/InVDXJCHLww",
    thumbnail: "https://i.ibb.co/Vp6NGyb/maxresdefault-2.jpg",
    category: { id: "carrer_moves", index: 2 },
    liked: false,
    views: 19383,
  },

  {
    title: "Startup or Service Companies?",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/Zp8a0IskmkE",
    thumbnail: "https://i.ibb.co/9HM3xgS/maxresdefault-1.jpg",
    category: { id: "carrer_moves", index: 3 },
    liked: false,
    views: 23232,
  },

  {
    title: "Masters or not?",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/JbGjZk_EQpg",
    thumbnail: "https://i.ibb.co/pbKWLRx/sddefault.jpg",
    category: { id: "carrer_moves", index: 4 },
    liked: false,
    views: 21132,
  },

  {
    title: "launching neog.camp: roadmap to full stack dev",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/Ezk2AwqgS9Q",
    thumbnail: "https://i.ibb.co/SN9w8dk/maxresdefault-6.jpg",
    category: { id: "neog_camp", index: 1 },
    liked: false,
    views: 26469,
  },

  {
    title: "First CLI App: Intro to programming",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/_L-UszPmy2A",
    thumbnail: "https://i.ibb.co/1bNTD69/maxresdefault-5.jpg",
    category: { id: "neog_camp", index: 2 },

    liked: false,
    views: 46600,
  },

  {
    title: "Getting started with Git, VSCode and Hosting",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "//www.youtube.com/embed/MMEIVh49pS8",
    thumbnail: "https://i.ibb.co/4gT7wx2/maxresdefault-4.jpg",
    category: { id: "neog_camp", index: 3 },

    liked: false,
    views: 22143,
  },

  {
    title: "Getting started with HTML5",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/No8qdcVYiQw",
    thumbnail: "https://i.ibb.co/Sx3MtL3/maxresdefault-3.jpg",
    category: { id: "neog_camp", index: 4 },
    liked: false,
    views: 18266,
  },
  {
    title: "Getting started with CSS3",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/u6_a0d94A1Q",
    thumbnail: "https://i.ibb.co/zfGHRVz/maxresdefault-2.jpg",
    category: { id: "neog_camp", index: 5 },
    liked: false,
    views: 19546,
  },
  {
    title: "JavaScript in the browser!",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/yLZazznWoAs",
    thumbnail: "https://i.ibb.co/MBxTbbZ/maxresdefault-1.jpg",
    category: { id: "neog_camp", index: 6 },
    liked: false,
    views: 21332,
  },
  {
    title: "First React App: Introduction to ReactJS library",
    mentorName: "Tanay Pratap",
    mentorId: "tanay_pratap",
    profile: "https://i.ibb.co/sm9Vrm6/tanay.png",

    embededLink: "https://www.youtube.com/embed/KUJsaM-hAjs",
    thumbnail: "https://i.ibb.co/8xP6nrh/maxresdefault.jpg",
    category: { id: "neog_camp", index: 7 },

    liked: false,
    views: 17652,
  },
];

export const videoData = videos.map((item, index) => {
  return { ...item, videoId: `${item.mentorId}_${index}` };
});
