export const English = {
  home: "Home",
  mentors: "Mentors",
  search: "Search",
  liked: "liked Video's",
  playlist: "Playlist",
  later: "Watch Later",
  history: "History",
  login: "Login",
  logout: "Logout",
  choose: "Choose your mentor",
  developed: "Developed by",
  explore: "Explore",
  recommend: "Recommended",
  more: "Show More",
  startLearning: "Start Learning",
  auth: {
    name: "Name",
    email: "Email",
    password: "Password",
    signin: "Sign in",
    signup: "Sign up",
    msg1: "not a member yet ?",
    msg2: "Already a member ?",
  },
  mentor: [
    { name: "Tanay Pratap", mentor: "Tech Mentor", route: "" },
    { name: "Varun Mavya", mentor: "Business Mentor", route: "" },
    { name: "Shashank Udapa", mentor: "Finance Mentor", route: "" },
    { name: "Abhinav Arora", mentor: "Marketing Mentor", route: "" },
    { name: "Abhinav Chikara", mentor: "Design Mentor", route: "" },
    { name: "Prakhar Gupta", mentor: "Conversation Mentor", route: "" },
  ],
};

export const Hindi = {
  home: "घर",
  mentors: "गुरु",
  search: "खोज कर",
  liked: "पसंद किया",
  playlist: "प्लेलिस्ट",
  later: "बाद में देखना",
  history: "इतिहास",
  login: "लॉग इन करें",
  logout: "लॉग आउट",
  choose: "अपना गुरु चुनें",
  startLearning: "सीखना शुरू करें",
  auth: {
    name: "नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    signin: "साइन इन",
    signup: "साइन अप ",
    msg1: "अभी तक सदस्य नहीं?",
    msg2: "पहले से ही एक सदस्य?",
  },

  mentor: [
    { name: "तनय प्रताप", mentor: "टेक मेंटर" },
    { name: "वरुण माव्या", mentor: "बिजनेस मेंटर" },
    { name: "शशांक उडुपा", mentor: "वित्त मेंटर" },
    { name: "अभिनव अरोड़", mentor: "मार्केटिंग मेंटर" },
    { name: "अभिनव छिकारा", mentor: "डिजाइन मेंटर" },
    { name: "प्रखर गुप्", mentor: "बातचीत मेंटर" },
  ],
};

export const Gujarati = {
  home: "ઘર",
  mentors: "માર્ગદર્શકો",
  search: "શોધ",
  liked: "ગમ્યું",
  playlist: "પ્લેલિસ્ટ",
  later: "પછી જુઓ",
  history: "ઇતિહાસ",
  login: "પ્રવેશ કરો",
  logout: "લૉગ આઉટ",
  choose: "તમારા માર્ગદર્શકને પસંદ કરો",
  startLearning: "લર્નિંગ શરૂ કરો",
  auth: {
    name: "નામ",
    email: "ઇમેઇલ",
    password: "પાસવર્ડ",
    signin: "સાઇન ઇન",
    signup: "સાઇન અપ કરો",
    msg1: "હજી સુધી સભ્ય નથી ?",
    msg2: "પહેલેથી સભ્ય છે?",
  },

  mentor: [
    { name: "તનય પ્રતાપ", mentor: "  ટેક માર્ગદર્શક" },
    { name: "વરુણ માવ્યા", mentor: "વ્યાપાર માર્ગદર્શક " },
    { name: "શશાંક ઉદુપા", mentor: "નાણાં માર્ગદર્શક" },
    { name: "અભિનવ અરોરા", mentor: "માર્કેટિંગ માર્ગદર્શક" },
    { name: "અભિનવ છિકારા", mentor: "ડિઝાઇન માર્ગદર્શક" },
    { name: "પ્રખર ગુપ્", mentor: "વાતચીત માર્ગદર્શક" },
  ],
};

export const Bangla = {
  home: "বাড়",
  mentors: "পরামর্শদাতা",
  search: "অনুসন্ধান",
  liked: "পছন্দ হয়েছে",
  playlist: "লেলিস্",
  later: "পরে দেখুন",
  history: "ইতিহাস",
  login: "রবেশ করুন",
  logout: "রস্থান",
  choose: "আপনার পরামর্শদাতা চয়ন করুন",
  startLearning: "শেখা শুরু করো",
  auth: {
    name: "নাম",
    email: "ইমেল",
    password: "ইমেল",
    signin: "সাইন ইন",
    signup: "সাইন আপ",
    msg1: "এখনও সদস্য নয় ?",
    msg2: "ইতিমধ্যে একজন সদস্য ?",
  },
  mentor: [
    { name: "তনয় প্রতাপ", mentor: "টেক মেন্টর" },
    { name: "বরুণ মাব্", mentor: "বিজনেস মেন্টর" },
    { name: "শশাঙ্ক উদূপা", mentor: "ফিনান্স মেন্টর" },
    { name: "অভিনব অরোরা", mentor: "বিপণন পরামর্শদাতা" },
    { name: "অভিনব ছিকার", mentor: "ডিজাইন মেন্টর" },
    { name: "প্রখর গুপ্", mentor: "কথোপকথন পরামর্শদাতা" },
  ],
};

export const Marathi = {
  home: "मुख्यपृष्ठ",
  mentors: "गुरू",
  search: "शोध",
  liked: "आवडले",
  playlist: "प्लेलिस्",
  later: "नंतर पहा",
  history: "इतिहास",
  login: "लॉगिन",
  logout: "बाहेर पडणे",
  choose: "आपला गुरू निवडा",
  startLearning: "शिकणे प्रारंभ करा",
  auth: {
    name: "नाव",
    email: "ईमेल",
    password: "संकेतशब्द",
    signin: "साइन इन",
    signup: "साइन अप",
    msg1: "अद्याप सदस्य नाही ?",
    msg2: "आधीच सदस्य आहात ?",
  },
  mentor: [
    { name: "तनय प्रताप", mentor: "टेक मेंटर" },
    { name: "वरुण माव्या", mentor: "व्यवसाय मार्गदर्शक" },
    { name: "शशांक उडुपा", mentor: "वित्त मार्गदर्शक" },
    { name: "अभिनव अरोरा", mentor: "विपणन मार्गदर्शक" },
    { name: "अभिनव चिकारा", mentor: "डिझाइन मेंटर" },
    { name: "प्राखर गुप्ता", mentor: "संभाषण मार्गदर्शक" },
  ],
};

export const Spanish = {
  home: "casa",
  mentors: "mentores",
  search: "buscar",
  liked: "gustó",
  playlist: "lista de",
  later: "ver despues",
  history: "historia",
  login: "acceso",
  logout: "cerrar sesión",
  choose: "Elige tu mentora",
  startLearning: "Comienza a aprender",
  auth: {
    name: "nombre",
    email: "Correo electrónico",
    password: "Contraseña",
    signin: "Iniciar sesión",
    signup: "Registrarse",
    msg1: "aún no eres miembro ?",
    msg2: "Ya eres miembro ?",
  },

  mentor: [
    { name: "Tanay Pratap", mentor: " Mentor Tecnológico" },
    { name: "Varun Mavya", mentor: " Mentor de negocios" },
    { name: "Shashank Udapa", mentor: " Mentor de finanzas" },
    { name: "Abhinav Arora", mentor: " Mentor de marketing" },
    { name: "Abhinav Chikara", mentor: " Mentor de diseño" },
    { name: "Prakhar Gupta", mentor: " Mentor de conversación" },
  ],
};
export const French = {
  home: "domicile",
  mentors: "mentors",
  search: "rechercher",
  liked: "aimé",
  playlist: "playlist",
  later: "regarder plus tard",
  history: "l'histoire",
  login: "connexion",
  logout: "Se déconnecter",
  choose: "Choisissez votre mentor",
  startLearning: "Commencer à apprendre",
  auth: {
    name: "nom",
    email: "Email",
    password: "Mot de passe",
    signin: "Connexion",
    signup: "Inscription",
    msg1: "pas encore membre ?",
    msg2: "Déjà membre ?",
  },
  mentor: [
    { name: "Tanay Pratap", mentor: "Mentor technique" },
    { name: "Varun Mavya", mentor: "Mentor d'affaires" },
    { name: "Shashank Udapa", mentor: "Mentor des finances" },
    { name: "Abhinav Arora", mentor: "Mentor marketing" },
    { name: "Abhinav Chikara", mentor: "Mentor en conception" },
    { name: "Prakhar Gupta", mentor: "Mentor de conversation" },
  ],
};

export const Italian = {
  home: "casa",
  mentors: "mentori",
  search: "ricerca",
  liked: "è piaciuto",
  playlist: "elenco di",
  later: "riproduzione",
  history: "guardare in seguito",
  login: "Accedere",
  logout: "disconnettersi",
  choose: "Scegli il tuo mentore",
  startLearning: "Inizia ad imparare",
  auth: {
    name: "Nome",
    email: "Email",
    password: "Password",
    signin: "Accedi",
    signup: "Registrati",
    msg1: "non sei ancora un membro ?",
    msg2: "Sei già un membro ?",
  },
  mentor: [
    { name: "Tanay Pratap", mentor: "Mentore tecnologico" },
    { name: "Varun Mavya", mentor: "Mentore aziendale" },
    { name: "Shashank Udapa", mentor: "Mentore finanziario" },
    { name: "Abhinav Arora", mentor: "Mentore di marketing" },
    { name: "Abhinav Chikara", mentor: "Mentore del design" },
    { name: "Prakhar Gupta", mentor: "Mentore di conversazione" },
  ],
};
